### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by Tsiangana** [rogerio-jose-gastao/BookDashPy#1]
O github diz q estas a trabalhar com C++ mais não consigo acha-lo no projeto, poderias explicar-me sobre o projeto, sua funcionalidade e as IDEs q usas e todas outras cenas...

**Comment by rogerio-jose-gastao** [comment]
Claro, estou a criar um site de analise de dados de livros usando python
Os usos de C++ e outras linguagens no código estão nas biblitecas que usei que são Streamlit, Pandas e Plotly
